#
# @(#)Makefile
#
# Copyright 2001, Aaron Ardiri     (mailto:aaron@ardiri.com)
#                 Charles Kerchner (mailto:chip@ardiri.com)
# All rights reserved.
# 
# The contents of this file is confidential and proprietrary in nature 
# ("Confidential Information"). Redistribution or modification without 
# prior consent of the original author(s) is prohibited.
#

# compile requirements
all:
	cp level-01-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-01-data.bmp

	cp level-02-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-02-data.bmp

	cp level-03-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-03-data.bmp

	cp level-04-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-04-data.bmp

	cp level-05-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-05-data.bmp

	cp level-06-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-06-data.bmp

	cp level-07-original.bmp in.bmp
	alchemy -u 2 -zh 3 -zo 4 -d0 -o -w in.bmp out.bmp
	cp out.bmp level-07-data.bmp

	rm in.bmp
	rm out.bmp

# clean-up funtions
clean:
	rm *data.bmp
